blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/jeffrdutton/vibe-validate/discussions
    about: Ask questions, share ideas, or discuss vibe-validate with the community
  - name: 📚 Documentation
    url: https://github.com/jeffrdutton/vibe-validate#readme
    about: Read the official documentation and guides
  - name: 🔒 Security Vulnerability
    url: https://github.com/jeffrdutton/vibe-validate/security/advisories/new
    about: Report a security vulnerability (private disclosure)
