name: Feature Request
description: Suggest a new feature or enhancement for vibe-validate
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? Is your feature request related to a specific pain point?
      placeholder: |
        I'm frustrated when...
        It's difficult to...
        I wish I could...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Be as specific as possible.
      placeholder: |
        I would like vibe-validate to...
        This could work by...
        Example usage: `vibe-validate ...`
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: use-case
    attributes:
      label: Primary Use Case
      description: Which scenario best describes your use case?
      options:
        - AI-assisted development (Claude Code, Cursor, etc.)
        - CI/CD pipeline automation
        - Local development workflow
        - Team collaboration
        - Other
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How much would this feature improve your workflow?
      options:
        - Critical - Blocking my adoption of vibe-validate
        - High - Would significantly improve my workflow
        - Medium - Nice to have, but I can work around it
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Configuration or Usage
      description: |
        If applicable, provide example configuration or usage showing how this feature would work.
      render: javascript
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Any other context, screenshots, or examples that help explain the feature request?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting:
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have reviewed the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature aligns with the goals of vibe-validate (LLM-friendly validation orchestration)
          required: true

  - type: textarea
    id: contribution
    attributes:
      label: Contribution
      description: |
        Would you be interested in contributing this feature yourself? (No obligation!)
      placeholder: |
        - I'd like to implement this myself with guidance
        - I can help test this feature
        - I prefer to let the maintainers handle this
    validations:
      required: false
